# Generated by Django 3.1.2 on 2023-07-08 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesCompra',
            fields=[
                ('orden', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='historial',
            name='id',
        ),
        migrations.AddField(
            model_name='historial',
            name='idHistorial',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historial',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.detallescompra'),
        ),
    ]
